### ISSUE TITLE
boilergql.GetPreloadModsWithLevel generated with invalid amount of args

### ISSUE THREAD

**Issue by troian** [web-ridge/gqlgen-sqlboiler#24]
```
mods := boilergql.GetPreloadModsWithLevel(ctx, AgreementPreloadMap, AgreementPayloadPreloadLevels.Agreement)
```

There is expected one more argument `level`

**Comment by RichardLindhout** [comment]
This behaviour of preloads is changed as of v2.0.11.

I did refactor preloads since it did only go a few levels deep and it created really big files. Sorry for the big changes a.t.m.

Please re-generate your code with: v2.0.12.

If you have custom code which you don't want gqlgen-sqlboiler to override please I use resolver_custom.go to put in custom code.

You also need to update github.com/web-ridge/utils-go/boilergql@master

You can see which changes it generates
```
https://github.com/web-ridge/gqlgen-sqlboiler-examples/commit/50235be907ceb4ccc4cec2b37a4e4b6b18eb10f3
```

**Comment by RichardLindhout** [comment]
![Schermafbeelding 2020-05-11 om 21 06 44](https://user-images.githubusercontent.com/6492229/81601557-5613be00-93cb-11ea-9ff9-cb3d7e2d872e.png)


This change was unavoidable because I generated over 100,000 lines of code for the preloads in my own program. In the examples, 11,000 lines of generated code could now also be removed.
